AWSTemplateFormatVersion: "2010-09-09"
Description: "Deploys the Hashicorp Vault helm chart into a Kubernetes cluster (qp-1qmcrhdml)"
Metadata:
  QSLint:
    Exclusions: [W9002, W9003, W9004, W9006]
Parameters:
  ClusterName:
    Type: String
    Description: Amazon EKS Cluster
  ConsulVersion:
    Type: String
    Default: "1.7.2"
    AllowedValues: 
    - "1.7.2"
Resources:
  ConsulHelmChart:
    Type: "AWSQS::Kubernetes::Helm"
    Properties:
      ClusterID: !Ref ClusterName
      Repository: https://helm.releases.hashicorp.com
      Namespace: !Ref KubernetesNameSpace
      Name: consul
      Chart: hashicorp/consul
      ValuesYaml:
        global:
          name: "consul"
Outputs:
  ConsulReleaseName:
    Value: !Ref ConsulHelmChart


